hepsi:	derle	calistir

derle:
	
	g++ -I	./include/	-o	./lib/IMEINo.o	-c	./src/IMEINo.c	
	g++ -I	./include/	-o	./lib/Kisi.o	-c	./src/Kisi.c
	g++ -I	./include/	-o	./lib/KimlikNo.o	-c	./src/KimlikNo.c
	g++ -I	./include/	-o	./lib/RastgeleKisi.o	-c	./src/RastgeleKisi.c
	g++ -I	./include/	-o	./lib/Telefon.o		-c	./src/Telefon.c
	g++	-I	./include/	-o	./bin/odev3	./lib/IMEINo.o	./lib/Kisi.o	./lib/KimlikNo.o	./lib/RastgeleKisi.o	./lib/Telefon.o		./src/Odev3Pdp.c


calistir:
	./bin/odev3