hepsi:	derle	calistir

derle:
	
	g++ -I	./include/	-o	./lib/Islem.o	-c	./src/Islem.cpp	
	g++ -I	./include/	-o	./lib/Agac.o	-c	./src/Agac.cpp
	g++ -I	./include/	-o	./lib/Liste.o	-c	./src/Liste.cpp
	g++ -I	./include/	-o	./lib/Dugum.o	-c	./src/dugum.cpp
	g++	-I	./include/	-o	./bin/odev3	./lib/Islem.o	./lib/Liste.o	./lib/Agac.o	./lib/Dugum.o	./src/veri.cpp


calistir:
	./bin/odev3