hepsi:	derle	calistir

derle:
	
	g++ -I	./include/	-o	./lib/Huffman.o	-c	./src/huffman.cpp
	g++ -I	./include/	-o	./lib/Dugum.o	-c	./src/dugum.cpp
	g++	-I	./include/	-o	./bin/odev4		./lib/Huffman.o	./lib/Dugum.o	./src/veri4.cpp


calistir:
	./bin/odev4